"""
QuantPilot - agent/schemas.py
Shared data models used across the agent, backtester, and API.
Using Pydantic gives us validation + easy JSON serialization for
storing agent reasoning trails in the database.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import List, Optional
from pydantic import BaseModel, Field, ConfigDict


def utcnow() -> datetime:
    """Timezone-aware UTC now — replaces deprecated datetime.utcnow()."""
    return datetime.now(timezone.utc)


class SignalDirection(str, Enum):
    LONG = "long"
    SHORT = "short"
    NEUTRAL = "neutral"


class ReasoningStep(BaseModel):
    """One step in the agent's chain of thought — fully auditable."""
    step_number: int
    tool_used: str               # e.g. "news_search", "sec_filing_reader", "price_fetch"
    tool_input: str
    tool_output_summary: str     # truncated/summarised, not the raw dump
    thought: str                 # the agent's reasoning at this step
    timestamp: datetime = Field(default_factory=utcnow)


class TradeHypothesis(BaseModel):
    """
    A single trade idea generated by the agent, with full provenance.
    This is what gets persisted to Postgres and what the backtester consumes.
    """
    id: Optional[int] = None
    ticker: str
    direction: SignalDirection
    thesis: str                          # one-paragraph natural language rationale
    confidence: float = Field(ge=0.0, le=1.0)
    horizon_days: int = Field(gt=0, default=5)
    entry_price_hint: Optional[float] = None
    reasoning_trail: List[ReasoningStep] = Field(default_factory=list)
    source_refs: List[str] = Field(default_factory=list)   # URLs / filing IDs cited
    created_at: datetime = Field(default_factory=utcnow)

    model_config = ConfigDict(use_enum_values=True)


class BacktestResult(BaseModel):
    """Result of running one hypothesis through the backtesting engine."""
    hypothesis_id: int
    ticker: str
    direction: SignalDirection
    entry_date: datetime
    exit_date: datetime
    entry_price: float
    exit_price: float
    pnl_pct: float
    max_drawdown_pct: float
    sharpe_ratio: Optional[float] = None
    win: bool
    benchmark_pnl_pct: Optional[float] = None   # vs buy-and-hold SPY over same period

    model_config = ConfigDict(use_enum_values=True)


class PortfolioStats(BaseModel):
    """Aggregate stats across all backtested hypotheses — for the dashboard."""
    total_hypotheses: int
    win_rate: float
    avg_pnl_pct: float
    avg_sharpe: Optional[float]
    best_trade_pnl: float
    worst_trade_pnl: float
    total_simulated_pnl_pct: float
